language: node_js
node_js:
- '6'
before_install: 
- npm install mocha istanbul
install:
- npm install
before_script:
- npm link .
script:
- ./ci/build.js
- ./ci/test.js
- ./ci/cover.js
- ./ci/report.js
env:
  global:
    secure: QNY+5yzpumBqGtFNBktFZ0MFwuLyHo6hjt78zOETFoWQyv13uZNk/SkwUGNwv8qPrnKRLxJcqJIu4ZnbvBj0F1zak2ESkuqzHSdvttgHTltoAJJVooDojO1kmR0OS40JuCDgK82ctB0A9MeMhchtkEne4N+TnEPd6Yvo0K7HxytodhUywO4cguQQ9kTeE5AZ8FRC/65gBzdhjW0rASUYvY0LQipYSfr8KsuAcJEdTFIaN4LK/LEC3N1uQiX153V3fb9clZBFQLxe5h4dNDO4liTYMS91cT2L7RFG5YpfwDVwHkNS+hSOuSBw/V0ssFPu4I7VZe6pKJezBjQna9BmyCN8C76ejGmjtLoDAXtWaYSxFslNnL56iJU/tXckNPw4YO4SnKCUS6+GIBhChEYdSZ3ie5kQp9B/GSs+dyrZ6/Fe8kdDs1gan4dLEHm96w9cjCJHcqYeYvu1rGhY5IfRHfCyr5i11UFDXrGeQ7Bm2Digorx+9nzxPQBiOF3qhIHb/yFFsBpFBHzGBjTyyRpHnfuN0t8a134UDEejA3yOYCEq1WndaXXKkvn67LqbShaAZUPgfRy0sG/NDBrPaX9Behoi32G+gBEo+tzEGud883JXynbbOKbCsbHSLYd2HBDgyq5q/+YMgrj1iNnZ1u0LlKC7FpUFEZImPLRau3K8umE=
